CREATE OR REPLACE FUNCTION highway_is_link(highway text) RETURNS boolean AS
$$
SELECT highway LIKE '%_link';
$$ LANGUAGE SQL IMMUTABLE
                STRICT
                PARALLEL SAFE;


-- etldoc: layer_transportation[shape=record fillcolor=lightpink, style="rounded,filled",
-- etldoc:     label="<sql> layer_transportation |<z4> z4 |<z5> z5 |<z6> z6 |<z7> z7 |<z8> z8 |<z9> z9 |<z10> z10 |<z11> z11 |<z12> z12|<z13> z13|<z14_> z14+" ] ;
CREATE OR REPLACE FUNCTION layer_transportation(bbox geometry, zoom_level int)
    RETURNS TABLE
            (
                osm_id     bigint,
                geometry   geometry,
                class      text,
                subclass   text,
                network    text,
                ramp       int,
                oneway     int,
                junction   text,
                motorroad  int,
                brunnel    text,
                service    text,
                access     text,
                toll       int,
                expressway int,
                layer      int,
                level      int,
                indoor     int,
                segregated text,
                bicycle    text,
                is_bicycle_road int,
                bicycle_all    text,
                bicycle_forward text,
                bicycle_backward text,
                cycleway_all   text,
                cycleway_left text,
                cycleway_right text,
                maxspeed_all   int,
                traffic_sign_all text,
                traffic_sign_is_mandatory boolean,
                traffic_sign_is_optional boolean,
                width      float,
                width_carriageway float,
                foot       text,
                horse      text,
                mtb_scale  text,
                surface    text,
                surface_osm text
            )
AS
$$
SELECT osm_id,
       geometry,
       CASE
           WHEN highway <> '' OR public_transport <> ''
               THEN highway_class(highway, public_transport, construction)
           WHEN railway <> '' THEN railway_class(railway)
           WHEN aerialway <> '' THEN 'aerialway'
           WHEN shipway <> '' THEN shipway
           WHEN man_made <> '' THEN man_made
           END AS class,
       CASE
           WHEN railway IS NOT NULL THEN railway
           WHEN (highway IS NOT NULL OR public_transport IS NOT NULL)
               AND highway_class(highway, public_transport, construction) = 'path'
               THEN COALESCE(NULLIF(public_transport, ''), highway)
           WHEN aerialway IS NOT NULL THEN aerialway
           END AS subclass,
       NULLIF(network, '') AS network,
       -- All links are considered as ramps as well
       CASE
           WHEN highway_is_link(highway)
             OR is_ramp
               THEN 1 END AS ramp,
       CASE WHEN is_oneway <> 0 THEN is_oneway::int END AS oneway,
       NULLIF(junction,''),
       CASE WHEN is_motorroad = TRUE THEN 1 END AS motorroad,
       brunnel(is_bridge, is_tunnel, is_ford) AS brunnel,
       NULLIF(service, '') AS service,
       access,
       CASE WHEN toll = TRUE THEN 1 END AS toll,
       CASE WHEN highway NOT IN ('', 'motorway') AND expressway = TRUE THEN 1 END AS expressway,
       NULLIF(layer, 0) AS layer,
       "level",
       CASE WHEN indoor = TRUE THEN 1 END AS indoor,
       NULLIF(segregated, '') AS segregated,
       NULLIF(bicycle, '') AS bicycle,
       CASE WHEN is_bicycle_road = TRUE THEN 1 END AS is_bicycle_road,
       NULLIF(bicycle_all, '') AS bicycle_all,
       NULLIF(bicycle_forward, '') AS bicycle_forward,
       NULLIF(bicycle_backward, '') AS bicycle_backward,
       NULLIF(cycleway_all, '') AS cycleway_all,
       NULLIF(cycleway_left, '') AS cycleway_left,
       NULLIF(cycleway_right, '') AS cycleway_right,
       NULLIF(maxspeed_all, 0) AS maxspeed_all,
       NULLIF(traffic_sign_all, '') AS traffic_sign_all,
       NULLIF(traffic_sign_all ~ '^DE.*(240|237|244.1|241)', false) AS traffic_sign_is_mandatory,
       NULLIF(traffic_sign_all ~ '^DE.*1022-10', false) AS traffic_sign_is_optional,
       CASE WHEN regexp_replace(width, '\s*m\s*$', '') ~ '^([0-9]+[.]?[0-9]*|[.][0-9]+)$' THEN CAST(regexp_replace(width, '\s*m\s*$', '') AS float) ELSE NULL::float END AS width,
       CASE WHEN regexp_replace(width_carriageway, '\s*m\s*$', '') ~ '^([0-9]+[.]?[0-9]*|[.][0-9]+)$' THEN CAST(regexp_replace(width_carriageway, '\s*m\s*$', '') AS float) ELSE NULL::float END AS width_carriageway,
       NULLIF(foot, '') AS foot,
       NULLIF(horse, '') AS horse,
       NULLIF(mtb_scale, '') AS mtb_scale,
       NULLIF(surface, '') AS surface,
       NULLIF(surface_osm, '') AS surface_osm
FROM (
         -- etldoc: osm_transportation_merge_linestring_gen_z4 -> layer_transportation:z4
         SELECT osm_id,
                geometry,
                highway,
                construction,
                network,
                NULL AS railway,
                NULL AS aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                NULL AS service,
                NULL AS access,
                NULL::boolean AS toll,
                is_bridge,
                is_tunnel,
                is_ford,
                NULL::boolean AS expressway,
                NULL::boolean AS is_ramp,
                NULL::int AS is_oneway,
                NULL AS junction,
                is_motorroad,
                NULL AS man_made,
                NULL::int AS layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_transportation_merge_linestring_gen_z4
         WHERE zoom_level = 4
         UNION ALL

         -- etldoc: osm_transportation_merge_linestring_gen_z5 -> layer_transportation:z5
         SELECT osm_id,
                geometry,
                highway,
                construction,
                network,
                NULL AS railway,
                NULL AS aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                NULL AS service,
                NULL AS access,
                NULL::boolean AS toll,
                is_bridge,
                is_tunnel,
                is_ford,
                NULL::boolean AS expressway,
                NULL::boolean AS is_ramp,
                NULL::int AS is_oneway,
                NULL AS junction,
                is_motorroad,
                NULL AS man_made,
                NULL::int AS layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_transportation_merge_linestring_gen_z5
         WHERE zoom_level = 5
         UNION ALL

         -- etldoc: osm_transportation_merge_linestring_gen_z6 -> layer_transportation:z6
         SELECT osm_id,
                geometry,
                highway,
                construction,
                network,
                NULL AS railway,
                NULL AS aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                NULL AS service,
                NULL AS access,
                NULL::boolean AS toll,
                is_bridge,
                is_tunnel,
                is_ford,
                NULL::boolean AS expressway,
                NULL::boolean AS is_ramp,
                NULL::int AS is_oneway,
                NULL AS junction,
                is_motorroad,
                NULL AS man_made,
                NULL::int AS layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_transportation_merge_linestring_gen_z6
         WHERE zoom_level = 6
         UNION ALL

         -- etldoc: osm_transportation_merge_linestring_gen_z7  ->  layer_transportation:z7
         SELECT osm_id,
                geometry,
                highway,
                construction,
                network,
                NULL AS railway,
                NULL AS aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                NULL AS service,
                NULL AS access,
                NULL::boolean AS toll,
                is_bridge,
                is_tunnel,
                is_ford,
                expressway,
                NULL::boolean AS is_ramp,
                NULL::int AS is_oneway,
                NULL AS junction,
                is_motorroad,
                NULL AS man_made,
                NULL::int AS layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_transportation_merge_linestring_gen_z7
         WHERE zoom_level = 7
         UNION ALL

         -- etldoc: osm_transportation_merge_linestring_gen_z8  ->  layer_transportation:z8
         SELECT osm_id,
                geometry,
                highway,
                construction,
                network,
                NULL AS railway,
                NULL AS aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                NULL AS service,
                NULL AS access,
                NULL::boolean AS toll,
                is_bridge,
                is_tunnel,
                is_ford,
                expressway,
                NULL::boolean AS is_ramp,
                NULL::int AS is_oneway,
                NULL AS junction,
                is_motorroad,
                NULL AS man_made,
                NULL::int AS layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                bicycle,
                NULL::boolean AS is_bicycle_road,
                bicycle_all(bicycle, bicycle_forward, bicycle_backward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle, sidewalk_right_bicycle) AS bicycle_all,
                bicycle_forward(bicycle, bicycle_forward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_right_bicycle) AS bicycle_forward,
                bicycle_backward(bicycle, bicycle_backward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle) AS bicycle_backward,
                cycleway_all(cycleway, cycleway_both, cycleway_left, cycleway_right, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle, sidewalk_right_bicycle) AS cycleway_all,
                cycleway_left(cycleway, cycleway_both, cycleway_left, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle) AS cycleway_left,
                cycleway_right(cycleway, cycleway_both, cycleway_right, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_right_bicycle) AS cycleway_right,
                maxspeed_all(maxspeed, maxspeed_forward, maxspeed_backward) AS maxspeed_all,
                NULL AS traffic_sign_all,
                width,
                width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_transportation_merge_linestring_gen_z8
         WHERE zoom_level = 8
         UNION ALL

         -- etldoc: osm_transportation_merge_linestring_gen_z9  ->  layer_transportation:z9
         SELECT osm_id,
                geometry,
                highway,
                construction,
                network,
                NULL AS railway,
                NULL AS aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                NULL AS service,
                access,
                toll,
                is_bridge,
                is_tunnel,
                is_ford,
                expressway,
                NULL::boolean AS is_ramp,
                NULL::int AS is_oneway,
                NULL AS junction,
                is_motorroad,
                NULL AS man_made,
                layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                segregated,
                bicycle,
                is_bicycle_road,
                bicycle_all(bicycle, bicycle_forward, bicycle_backward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle, sidewalk_right_bicycle) AS bicycle_all,
                bicycle_forward(bicycle, bicycle_forward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_right_bicycle) AS bicycle_forward,
                bicycle_backward(bicycle, bicycle_backward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle) AS bicycle_backward,
                cycleway_all(cycleway, cycleway_both, cycleway_left, cycleway_right, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle, sidewalk_right_bicycle) AS cycleway_all,
                cycleway_left(cycleway, cycleway_both, cycleway_left, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle) AS cycleway_left,
                cycleway_right(cycleway, cycleway_both, cycleway_right, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_right_bicycle) AS cycleway_right,
                maxspeed_all(maxspeed, maxspeed_forward, maxspeed_backward) AS maxspeed_all,
                traffic_sign_all(traffic_sign, traffic_sign_forward, traffic_sign_backward) AS traffic_sign_all,
                width,
                width_carriageway,
                foot,
                horse,
                mtb_scale,
                surface_value(surface) AS surface,
                surface AS surface_osm,
                z_order
         FROM osm_transportation_merge_linestring_gen_z9
         WHERE zoom_level = 9
         UNION ALL

         -- etldoc: osm_transportation_merge_linestring_gen_z10  ->  layer_transportation:z10
         SELECT osm_id,
                geometry,
                highway,
                construction,
                network,
                NULL AS railway,
                NULL AS aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                NULL AS service,
                access,
                toll,
                is_bridge,
                is_tunnel,
                is_ford,
                expressway,
                NULL::boolean AS is_ramp,
                NULL::int AS is_oneway,
                NULL AS junction,
                is_motorroad,
                NULL AS man_made,
                layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                segregated,
                bicycle,
                is_bicycle_road,
                bicycle_all(bicycle, bicycle_forward, bicycle_backward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle, sidewalk_right_bicycle) AS bicycle_all,
                bicycle_forward(bicycle, bicycle_forward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_right_bicycle) AS bicycle_forward,
                bicycle_backward(bicycle, bicycle_backward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle) AS bicycle_backward,
                cycleway_all(cycleway, cycleway_both, cycleway_left, cycleway_right, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle, sidewalk_right_bicycle) AS cycleway_all,
                cycleway_left(cycleway, cycleway_both, cycleway_left, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle) AS cycleway_left,
                cycleway_right(cycleway, cycleway_both, cycleway_right, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_right_bicycle) AS cycleway_right,
                maxspeed_all(maxspeed, maxspeed_forward, maxspeed_backward) AS maxspeed_all,
                traffic_sign_all(traffic_sign, traffic_sign_forward, traffic_sign_backward) AS traffic_sign_all,
                width,
                width_carriageway,
                foot,
                horse,
                mtb_scale,
                surface_value(surface) AS surface,
                surface AS surface_osm,
                z_order
         FROM osm_transportation_merge_linestring_gen_z10
         WHERE zoom_level = 10
         UNION ALL

         -- etldoc: osm_transportation_merge_linestring_gen_z11  ->  layer_transportation:z11
         SELECT osm_id,
                geometry,
                highway,
                construction,
                network,
                NULL AS railway,
                NULL AS aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                NULL AS service,
                access,
                toll,
                is_bridge,
                is_tunnel,
                is_ford,
                expressway,
                NULL::boolean AS is_ramp,
                NULL::int AS is_oneway,
                NULL AS junction,
                is_motorroad,
                NULL AS man_made,
                layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                segregated,
                bicycle,
                is_bicycle_road,
                bicycle_all(bicycle, bicycle_forward, bicycle_backward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle, sidewalk_right_bicycle) AS bicycle_all,
                bicycle_forward(bicycle, bicycle_forward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_right_bicycle) AS bicycle_forward,
                bicycle_backward(bicycle, bicycle_backward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle) AS bicycle_backward,
                cycleway_all(cycleway, cycleway_both, cycleway_left, cycleway_right, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle, sidewalk_right_bicycle) AS cycleway_all,
                cycleway_left(cycleway, cycleway_both, cycleway_left, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle) AS cycleway_left,
                cycleway_right(cycleway, cycleway_both, cycleway_right, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_right_bicycle) AS cycleway_right,
                maxspeed_all(maxspeed, maxspeed_forward, maxspeed_backward) AS maxspeed_all,
                traffic_sign_all(traffic_sign, traffic_sign_forward, traffic_sign_backward) AS traffic_sign_all,
                width,
                width_carriageway,
                foot,
                horse,
                mtb_scale,
                surface_value(surface) AS surface,
                surface AS surface_osm,
                z_order
         FROM osm_transportation_merge_linestring_gen_z11
         WHERE zoom_level = 11
         UNION ALL

         -- etldoc: osm_highway_linestring  ->  layer_transportation:z12
         -- etldoc: osm_highway_linestring  ->  layer_transportation:z13
         -- etldoc: osm_highway_linestring  ->  layer_transportation:z14_
         -- etldoc: osm_transportation_name_network  ->  layer_transportation:z12
         -- etldoc: osm_transportation_name_network  ->  layer_transportation:z13
         -- etldoc: osm_transportation_name_network  ->  layer_transportation:z14_
         SELECT hl.osm_id,
                hl.geometry,
                hl.highway,
                construction,
                network,
                NULL AS railway,
                NULL AS aerialway,
                NULL AS shipway,
                public_transport,
                service_value(service) AS service,
                CASE WHEN access IN ('private', 'no') THEN 'no' END AS access,
                toll,
                is_bridge,
                is_tunnel,
                is_ford,
                expressway,
                is_ramp,
                is_oneway,
                junction,
                is_motorroad,
                man_made,
                hl.layer,
                CASE WHEN hl.highway IN ('footway', 'steps') THEN hl.level END AS level,
                CASE WHEN hl.highway IN ('footway', 'steps') THEN hl.indoor END AS indoor,
                segregated,
                bicycle,
                is_bicycle_road,
                bicycle_all(bicycle, bicycle_forward, bicycle_backward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle, sidewalk_right_bicycle) AS bicycle_all,
                bicycle_forward(bicycle, bicycle_forward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_right_bicycle) AS bicycle_forward,
                bicycle_backward(bicycle, bicycle_backward, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle) AS bicycle_backward,
                cycleway_all(cycleway, cycleway_both, cycleway_left, cycleway_right, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle, sidewalk_right_bicycle) AS cycleway_all,
                cycleway_left(cycleway, cycleway_both, cycleway_left, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_left_bicycle) AS cycleway_left,
                cycleway_right(cycleway, cycleway_both, cycleway_right, sidewalk_bicycle, sidewalk_both_bicycle, sidewalk_right_bicycle) AS cycleway_right,
                maxspeed_all(maxspeed, maxspeed_forward, maxspeed_backward) AS maxspeed_all,
                traffic_sign_all(traffic_sign, traffic_sign_forward, traffic_sign_backward) AS traffic_sign_all,
                width,
                width_carriageway,
                foot,
                horse,
                mtb_scale,
                surface_value(surface) AS "surface",
                surface AS surface_osm,
                hl.z_order
         FROM osm_highway_linestring hl
         LEFT OUTER JOIN osm_transportation_name_network n ON hl.osm_id = n.osm_id
         WHERE NOT is_area
           AND
               CASE WHEN zoom_level = 12 THEN
                         CASE WHEN transportation_filter_z12(hl.highway, hl.construction) THEN TRUE
                              WHEN hl.highway IN ('track', 'path') THEN n.route_rank = 1
                         END
                    WHEN zoom_level = 13 THEN
                         CASE WHEN man_made='pier' THEN NOT ST_IsClosed(hl.geometry)
                              WHEN hl.highway IN ('track', 'path') THEN (hl.name <> ''
                                                                   OR n.route_rank BETWEEN 1 AND 2
                                                                   OR hl.sac_scale <> ''
                                                                   )
                              ELSE transportation_filter_z13(hl.highway, public_transport, hl.construction, service)
                         END
                    WHEN zoom_level >= 14 THEN
                         CASE WHEN man_made='pier' THEN NOT ST_IsClosed(hl.geometry)
                              ELSE TRUE
                         END
               END
         UNION ALL

         -- etldoc: osm_railway_linestring_gen_z8  ->  layer_transportation:z8
         SELECT osm_id,
                geometry,
                NULL AS highway,
                NULL AS construction,
                NULL AS network,
                railway,
                NULL AS aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                service_value(service) AS service,
                NULL::text AS access,
                NULL::boolean AS toll,
                NULL::boolean AS is_bridge,
                NULL::boolean AS is_tunnel,
                NULL::boolean AS is_ford,
                NULL::boolean AS expressway,
                NULL::boolean AS is_ramp,
                NULL::int AS is_oneway,
                NULL AS junction,
                NULL::boolean AS is_motorroad,
                NULL AS man_made,
                NULL::int AS layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_railway_linestring_gen_z8
         WHERE zoom_level = 8
           AND railway = 'rail'
           AND service = ''
           AND usage = 'main'
         UNION ALL

         -- etldoc: osm_railway_linestring_gen_z9  ->  layer_transportation:z9
         SELECT osm_id,
                geometry,
                NULL AS highway,
                NULL AS construction,
                NULL AS network,
                railway,
                NULL AS aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                service_value(service) AS service,
                NULL::text AS access,
                NULL::boolean AS toll,
                NULL::boolean AS is_bridge,
                NULL::boolean AS is_tunnel,
                NULL::boolean AS is_ford,
                NULL::boolean AS expressway,
                NULL::boolean AS is_ramp,
                NULL::int AS is_oneway,
                NULL AS junction,
                NULL::boolean AS is_motorroad,
                NULL AS man_made,
                layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_railway_linestring_gen_z9
         WHERE zoom_level = 9
           AND railway = 'rail'
           AND service = ''
           AND usage = 'main'
         UNION ALL

         -- etldoc: osm_railway_linestring_gen_z10  ->  layer_transportation:z10
         SELECT osm_id,
                geometry,
                NULL AS highway,
                NULL AS construction,
                NULL AS network,
                railway,
                NULL AS aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                service_value(service) AS service,
                NULL::text AS access,
                NULL::boolean AS toll,
                is_bridge,
                is_tunnel,
                is_ford,
                NULL::boolean AS expressway,
                is_ramp,
                is_oneway,
                NULL AS junction,
                NULL::boolean AS is_motorroad,
                NULL AS man_made,
                layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_railway_linestring_gen_z10
         WHERE zoom_level = 10
           AND railway IN ('rail', 'narrow_gauge')
           AND service = ''
         UNION ALL

         -- etldoc: osm_railway_linestring_gen_z11  ->  layer_transportation:z11
         SELECT osm_id,
                geometry,
                NULL AS highway,
                NULL AS construction,
                NULL AS network,
                railway,
                NULL AS aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                service_value(service) AS service,
                NULL::text AS access,
                NULL::boolean AS toll,
                is_bridge,
                is_tunnel,
                is_ford,
                NULL::boolean AS expressway,
                is_ramp,
                is_oneway,
                NULL AS junction,
                NULL::boolean AS is_motorroad,
                NULL AS man_made,
                layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_railway_linestring_gen_z11
         WHERE zoom_level = 11
           AND railway IN ('rail', 'narrow_gauge', 'light_rail')
           AND service = ''
         UNION ALL

         -- etldoc: osm_railway_linestring_gen_z12  ->  layer_transportation:z12
         SELECT osm_id,
                geometry,
                NULL AS highway,
                NULL AS construction,
                NULL AS network,
                railway,
                NULL AS aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                service_value(service) AS service,
                NULL::text AS access,
                NULL::boolean AS toll,
                is_bridge,
                is_tunnel,
                is_ford,
                NULL::boolean AS expressway,
                is_ramp,
                is_oneway,
                NULL AS junction,
                NULL::boolean AS is_motorroad,
                NULL AS man_made,
                layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_railway_linestring_gen_z12
         WHERE zoom_level = 12
           AND railway IN ('rail', 'narrow_gauge', 'light_rail')
           AND service = ''
         UNION ALL

         -- etldoc: osm_railway_linestring ->  layer_transportation:z13
         -- etldoc: osm_railway_linestring ->  layer_transportation:z14_
         SELECT osm_id,
                geometry,
                NULL AS highway,
                NULL AS construction,
                NULL AS network,
                railway,
                NULL AS aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                service_value(service) AS service,
                NULL::text AS access,
                NULL::boolean AS toll,
                is_bridge,
                is_tunnel,
                is_ford,
                NULL::boolean AS expressway,
                is_ramp,
                is_oneway,
                NULL AS junction,
                NULL::boolean AS is_motorroad,
                NULL AS man_made,
                layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_railway_linestring
         WHERE zoom_level = 13
           AND railway IN ('rail', 'narrow_gauge', 'light_rail')
           AND service = ''
           OR zoom_level >= 14
         UNION ALL

         -- etldoc: osm_aerialway_linestring_gen_z12  ->  layer_transportation:z12
         SELECT osm_id,
                geometry,
                NULL AS highway,
                NULL AS construction,
                NULL AS network,
                NULL AS railway,
                aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                service_value(service) AS service,
                NULL::text AS access,
                NULL::boolean AS toll,
                is_bridge,
                is_tunnel,
                is_ford,
                NULL::boolean AS expressway,
                is_ramp,
                is_oneway,
                NULL AS junction,
                NULL::boolean AS is_motorroad,
                NULL AS man_made,
                layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_aerialway_linestring_gen_z12
         WHERE zoom_level = 12
         UNION ALL

         -- etldoc: osm_aerialway_linestring ->  layer_transportation:z13
         -- etldoc: osm_aerialway_linestring ->  layer_transportation:z14_
         SELECT osm_id,
                geometry,
                NULL AS highway,
                NULL AS construction,
                NULL AS network,
                NULL AS railway,
                aerialway,
                NULL AS shipway,
                NULL AS public_transport,
                service_value(service) AS service,
                NULL::text AS access,
                NULL::boolean AS toll,
                is_bridge,
                is_tunnel,
                is_ford,
                NULL::boolean AS expressway,
                is_ramp,
                is_oneway,
                NULL AS junction,
                NULL::boolean AS is_motorroad,
                NULL AS man_made,
                layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_aerialway_linestring
         WHERE zoom_level >= 13
         UNION ALL

         -- etldoc: osm_shipway_linestring_gen_z11  ->  layer_transportation:z11
         SELECT osm_id,
                geometry,
                NULL AS highway,
                NULL AS construction,
                NULL AS network,
                NULL AS railway,
                NULL AS aerialway,
                shipway,
                NULL AS public_transport,
                service_value(service) AS service,
                NULL::text AS access,
                NULL::boolean AS toll,
                is_bridge,
                is_tunnel,
                is_ford,
                NULL::boolean AS expressway,
                is_ramp,
                is_oneway,
                NULL AS junction,
                NULL::boolean AS is_motorroad,
                NULL AS man_made,
                layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_shipway_linestring_gen_z11
         WHERE zoom_level = 11
         UNION ALL

         -- etldoc: osm_shipway_linestring_gen_z12  ->  layer_transportation:z12
         SELECT osm_id,
                geometry,
                NULL AS highway,
                NULL AS construction,
                NULL AS network,
                NULL AS railway,
                NULL AS aerialway,
                shipway,
                NULL AS public_transport,
                service_value(service) AS service,
                NULL::text AS access,
                NULL::boolean AS toll,
                is_bridge,
                is_tunnel,
                is_ford,
                NULL::boolean AS expressway,
                is_ramp,
                is_oneway,
                NULL AS junction,
                NULL::boolean AS is_motorroad,
                NULL AS man_made,
                layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_shipway_linestring_gen_z12
         WHERE zoom_level = 12
         UNION ALL

         -- etldoc: osm_shipway_linestring ->  layer_transportation:z13
         -- etldoc: osm_shipway_linestring ->  layer_transportation:z14_
         SELECT osm_id,
                geometry,
                NULL AS highway,
                NULL AS construction,
                NULL AS network,
                NULL AS railway,
                NULL AS aerialway,
                shipway,
                NULL AS public_transport,
                service_value(service) AS service,
                NULL::text AS access,
                NULL::boolean AS toll,
                is_bridge,
                is_tunnel,
                is_ford,
                NULL::boolean AS expressway,
                is_ramp,
                is_oneway,
                NULL AS junction,
                NULL::boolean AS is_motorroad,
                NULL AS man_made,
                layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_shipway_linestring
         WHERE zoom_level >= 13
         UNION ALL

         -- NOTE: We limit the selection of polys because we need to be
         -- careful to net get false positives here because
         -- it is possible that closed linestrings appear both as
         -- highway linestrings and as polygon
         -- etldoc: osm_highway_polygon ->  layer_transportation:z13
         -- etldoc: osm_highway_polygon ->  layer_transportation:z14_
         SELECT osm_id,
                geometry,
                highway,
                NULL AS construction,
                NULL AS network,
                NULL AS railway,
                NULL AS aerialway,
                NULL AS shipway,
                public_transport,
                NULL AS service,
                NULL::text AS access,
                NULL::boolean AS toll,
                CASE
                    WHEN man_made IN ('bridge') THEN TRUE
                    ELSE FALSE
                    END AS is_bridge,
                FALSE AS is_tunnel,
                FALSE AS is_ford,
                NULL::boolean AS expressway,
                FALSE AS is_ramp,
                FALSE::int AS is_oneway,
                NULL AS junction,
                NULL::boolean AS is_motorroad,
                man_made,
                layer,
                NULL::int AS level,
                NULL::boolean AS indoor,
                NULL AS segregated,
                NULL AS bicycle,
                NULL::boolean AS is_bicycle_road,
                NULL AS bicycle_all,
                NULL AS bicycle_forward,
                NULL AS bicycle_backward,
                NULL AS cycleway_all,
                NULL AS cycleway_left,
                NULL AS cycleway_right,
                NULL::int AS maxspeed_all,
                NULL AS traffic_sign_all,
                NULL AS width,
                NULL AS width_carriageway,
                NULL AS foot,
                NULL AS horse,
                NULL AS mtb_scale,
                NULL AS surface,
                NULL AS surface_osm,
                z_order
         FROM osm_highway_polygon
              -- We do not want underground pedestrian areas for now
         WHERE zoom_level >= 13
           AND (
                 man_made IN ('bridge', 'pier')
                 OR (is_area AND COALESCE(layer, 0) >= 0)
             )
     ) AS zoom_levels
WHERE geometry && bbox
ORDER BY z_order ASC;
$$ LANGUAGE SQL STABLE
                -- STRICT
                PARALLEL SAFE;
